version: '3.8'

services:
  # PostgreSQL Database (Development)
  db:
    image: postgres:15-alpine
    container_name: callqualityhub_db_dev
    environment:
      POSTGRES_DB: qualityhub_dev
      POSTGRES_USER: qualityhubuser
      POSTGRES_PASSWORD: dev_password_123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis Cache (Development)
  redis:
    image: redis:7-alpine
    container_name: callqualityhub_redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Django Web Application (Development)
  web:
    build:
      context: .
      target: development
    container_name: callqualityhub_web_dev
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=qualityhub_dev
      - DB_USER=qualityhubuser
      - DB_PASSWORD=dev_password_123
      - SECRET_KEY=dev-secret-key-not-for-production
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app
      - media_dev_files:/app/media
      - logs_dev:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000

  # MailHog (Email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: callqualityhub_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  media_dev_files:
    driver: local
  logs_dev:
    driver: local

networks:
  default:
    name: callqualityhub_dev_network 